name: End-to-end tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Navigate to the correct subdirectory and install dependencies
      - name: Install dependencies
        run: |
          cd retool-demo-cloud/user
          npm install

      # Step 3: Run Cypress tests in headless mode
      - name: Run Cypress Tests
        run: |
          cd retool-demo-cloud/user
          npm run cypress:run

      # Step 4: Upload Cypress videos for debugging (optional)
      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: retool-demo-cloud/user/cypress/videos

      # Step 5: Upload Cypress screenshots for debugging (optional)
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: retool-demo-cloud/user/cypress/screenshots
