name: End-to-end tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Navigate to the correct subdirectory and install dependencies
      - name: Install dependencies
        run: |
          cd user
          npm install

      # Step 3: Run Cypress tests in headless mode using Chrome
      - name: Run Cypress Tests in Chrome
        run: |
          cd user
          npx cypress run --browser chrome --headless

      # Step 4: Upload Cypress videos for debugging (optional)
      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: user/cypress/videos

      # Step 5: Upload Cypress screenshots for debugging (optional)
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: user/cypress/screenshots
